<a href="https://colab.research.google.com/github/IlhamThrq/AI_TI-1B_2025/blob/main/Skalar%2C%20Vektor%2C%20dan%20Matriks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jobsheet 2 : OPERASI MATEMATIKA, VEKTOR, MATRIKS DAN TIPE DATA


## Operasi Matematika Menggunakan Python

### a. Mendapatkan Nilai Minimum dan Maksimum

In [2]:
x = min(5, 10, 25)
y = max(6, 12, 18)

print("Nilai minimum:", x)
print("Nilai maksimum:", y)

Nilai minimum: 5
Nilai maksimum: 18


### b. Mendapatkan Nilai Absolut

In [4]:
x = abs(-7.25)
print("Nilai absolut:", x)

Nilai absolut: 7.25


### C. Mendapatkan Nilai Pangkat

In [5]:
import math
x = math.pow(4, 3)

print("Hasil 4 pangkat 3:", x)

Hasil 4 pangkat 3: 64.0


### d. Mendapatkan Nilai Akar

In [7]:
import math
x = math.sqrt(64)

print("Akar kuadrat dari 64:", x)

Akar kuadrat dari 64: 8.0


### e. Mendapatkan Nilai Pembulatan

In [8]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)

print("Pembulatan ke atas (ceil):", x)
print("Pembulatan ke bawah (floor):", y)

Pembulatan ke atas (ceil): 2
Pembulatan ke bawah (floor): 1


### f. Mendapatkan Nilai Konstansta (PI)

In [9]:
import math
x = math.pi

print("Nilai π (pi):", x)

Nilai π (pi): 3.141592653589793


## Menggunakan Fungsi MATH

In [17]:
# Beberapa fungsi MATH yang tersedia dan dapat di panggil adalah sebagai berikut:

import math  # Mengimpor modul math

# Menggunakan berbagai fungsi dari math
angka = 125

print("Nilai sinus dari 125 derajat =", math.sin(math.radians(angka)))
print("Nilai cosinus dari 125 derajat =", math.cos(math.radians(angka)))
print("Nilai tangen dari 125 derajat =", math.tan(math.radians(angka)))

print("Logaritma natural dari 10 =", math.log(10))
print("Logaritma basis 10 dari 1000 =", math.log10(1000))

print("π/4 radian dalam derajat =", math.degrees(math.pi / 4))

# Menghitung jarak antara dua titik (3,4) dan (0,0)
p1 = (3, 4)
p2 = (0, 0)
print("Jarak Euclidean antara (3,4 dan (0,0) =", math.dist(p1, p2))

# Faktorial dari 10
print("Faktorial dari 10 =", math.factorial(10))

# Sisa pembagian dari 25 dibagi 7
print("Sisa pembagian 25 ÷ 7 =", math.fmod(25, 7))

# Mengecek apakah angka NaN (Not a Number)
nan_val = float('nan')
print("Apakah NaN?", math.isnan(nan_val))

# Menghitung nilai fungsi gamma dari 6
k = math.gamma(6)
print("Nilai fungsi gamma dari 6 =", k)

# Permutasi dari 5 elemen yang diambil 2
print("Permutasi 5P2 =", math.perm(5, 2))

Nilai sinus dari 125 derajat = 0.8191520442889917
Nilai cosinus dari 125 derajat = -0.5735764363510462
Nilai tangen dari 125 derajat = -1.4281480067421142
Logaritma natural dari 10 = 2.302585092994046
Logaritma basis 10 dari 1000 = 3.0
π/4 radian dalam derajat = 45.0
Jarak Euclidean antara (3,4 dan (0,0) = 5.0
Faktorial dari 10 = 3628800
Sisa pembagian 25 ÷ 7 = 4.0
Apakah NaN? True
Nilai fungsi gamma dari 6 = 120.0
Permutasi 5P2 = 20


## Operasi Matriks dan Vektor Dengan Python

### a. Membuat Matriks di Python

In [18]:
import numpy as np

A = np.array([[80, 30, 25],
              [50, 20, 10]])

B = np.array([[30, 60, 15],
              [10, 30, 30]])

hasil = A + B

print("Matriks A:\n", A)
print("Matriks B:\n", B)
print("Hasil penjumlahan A + B:\n", hasil)

Matriks A:
 [[80 30 25]
 [50 20 10]]
Matriks B:
 [[30 60 15]
 [10 30 30]]
Hasil penjumlahan A + B:
 [[110  90  40]
 [ 60  50  40]]


### b. Melakukan Operasi Dot Product

In [19]:
import numpy as np

A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)

print("Vektor A:", A)
print("Vektor B:", B)
print("Hasil dot product A . B:", hasil)

Vektor A: [10 20 15]
Vektor B: [16 67 35]
Hasil dot product A . B: 2025


### c. Melakukan Operasi Cross Product

In [20]:
import numpy as np

A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.cross(A, B)

print("Vektor A:", A)
print("Vektor B:", B)
print("Hasil cross product A × B:", hasil)

Vektor A: [10 20 15]
Vektor B: [16 67 35]
Hasil cross product A × B: [-305 -110  350]


## Tugas Praktikum

### 1. Tentukan Hasil Perkalian Berikut menggunakan kode python :

In [25]:
import numpy as np

A = np.array([[3, 1], [2, 0]])
B = np.array([[2, 1], [1, -1]])
C = np.array([[-1, 1, 2], [2, 0, -1]])

hasil_AxB = np.dot(A, B)
hasil_BxC = np.dot(B, C)

print("Jawaban No. 1")
print("a. A x B =\n", hasil_AxB)
print("b. B x C =\n",hasil_BxC)
print()

Jawaban No. 1
a. A x B =
 [[7 2]
 [4 2]]
b. B x C =
 [[ 0  2  3]
 [-3  1  3]]



### 2. Hitunglah nilai dari soal faktorial berikut

In [28]:
import math

# Menghitung faktorial
faktorial_6 = math.factorial(6)
faktorial_8 = math.factorial(8)
faktorial_5 = math.factorial(5)

# Operasi pembagian
pembagian_faktorial = faktorial_8 / faktorial_5

# Menampilkan hasil masing-masing jawaban
print("Jawaban No. 2")
print("a. 6! =", faktorial_6)
print("b. 8! / 5! =", pembagian_faktorial)


Jawaban No. 2
a. 6! = 720
b. 8! / 5! = 336.0


### 3. Dua Buah Vektor A dan B merupakan vektor 3D pada koordinat kartesian. Jika Vektor A = 5i + 3j + 7k dan Vektor B = 12i – 3j + k. Maka tentukan panjang masing-masing Vektor, hasil perkalian titik A.B, dan AxB.

In [29]:
import numpy as np

# Mendefinisikan vektor A dan B
A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

# Menghitung panjang masing-masing vektor (norma)
panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)
# Menghitung hasil perkalian titik (dot product)
dot_product = np.dot(A, B)

# Menghitung hasil perkalian silang (cross product)
cross_product = np.cross(A, B)

# Menampilkan hasil
print("Panjang vektor A:", panjang_A)
print("Panjang vektor B:", panjang_B)
print("Hasil perkalian titik (A . B):", dot_product)
print("Hasil perkalian silang (A x B):", cross_product)

Panjang vektor A: 9.1104335791443
Panjang vektor B: 12.409673645990857
Hasil perkalian titik (A . B): 58
Hasil perkalian silang (A x B): [ 24  79 -51]
